# Generated by Django 3.2.4 on 2021-06-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('room', 'start')},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
